import { useState } from 'react';
import { X, Download, FileJson, FileText, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { type Node, type Edge } from '@xyflow/react';
import { toast } from 'sonner';

interface ExportModalProps {
  open: boolean;
  onClose: () => void;
  nodes: Node[];
  edges: Edge[];
  spaceName?: string;
}

export function ExportModal({ open, onClose, nodes, edges, spaceName }: ExportModalProps) {
  const [exported, setExported] = useState<string | null>(null);

  if (!open) return null;

  const slug = (spaceName || 'canvas').toLowerCase().replace(/\s+/g, '-');
  const dateStr = new Date().toISOString().slice(0, 10);

  const downloadJSON = () => {
    const payload = {
      version: '2.0',
      exported_at: new Date().toISOString(),
      space_name: spaceName || 'canvas',
      nodes: nodes.map(n => ({
        id: n.id,
        type: n.type,
        position: n.position,
        data: {
          title: (n.data as any)?.title,
          prompt: (n.data as any)?.prompt,
          model: (n.data as any)?.model,
          status: (n.data as any)?.status,
          assetUrl: (n.data as any)?.assetUrl,
        },
      })),
      edges: edges.map(e => ({
        id: e.id,
        source: e.source,
        target: e.target,
        type: e.type,
      })),
    };

    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `creator-ia-${slug}-${dateStr}.json`;
    a.click();
    URL.revokeObjectURL(url);
    setExported('json');
    toast.success('Canvas exportado como JSON');
  };

  const downloadGenesis = () => {
    const components = nodes.map(n => {
      const data = n.data as any;
      return {
        id: n.id,
        type: n.type,
        name: data?.title || n.type,
        prompt: data?.prompt || '',
        model: data?.model || '',
        connections: edges
          .filter(e => e.source === n.id)
          .map(e => ({ target: e.target })),
      };
    });

    const genesisPayload = {
      schema: 'creator-ia-genesis-v1',
      app_name: spaceName || 'Creator IA Export',
      components,
      tech_stack: ['React', 'Tailwind CSS', 'TypeScript'],
      notes: 'Generated by Creator IA Pro Studio — creator-ia.com',
    };

    const blob = new Blob([JSON.stringify(genesisPayload, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `genesis-${slug}-${dateStr}.json`;
    a.click();
    URL.revokeObjectURL(url);
    setExported('genesis');
    toast.success('Exportado en formato Genesis');
  };

  const printPDF = () => {
    window.print();
    setExported('pdf');
    toast.success('Diálogo de impresión abierto — guarda como PDF');
  };

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center">
      <div className="absolute inset-0 bg-zinc-900/40 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full max-w-md mx-4 bg-white border border-zinc-200 rounded-[2rem] shadow-2xl animate-in fade-in zoom-in-95 duration-200 overflow-hidden">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-5 border-b border-zinc-100 bg-zinc-50/50">
          <div>
            <h2 className="text-sm font-bold text-zinc-900 font-sans">Exportar Canvas</h2>
            <p className="text-[10px] text-zinc-500 mt-0.5">{nodes.length} nodo{nodes.length !== 1 ? 's' : ''} · {edges.length} conex.</p>
          </div>
          <Button variant="ghost" size="icon" onClick={onClose} className="w-8 h-8 rounded-xl text-zinc-400 hover:text-zinc-600 hover:bg-zinc-100">
            <X className="w-4 h-4" />
          </Button>
        </div>

        {/* Options */}
        <div className="p-6 space-y-3">

          {/* JSON */}
          <button
            onClick={downloadJSON}
            className="w-full flex items-center gap-4 p-4 rounded-2xl border border-zinc-200 bg-zinc-50 hover:bg-zinc-100 hover:border-zinc-300 transition-all group text-left"
          >
            <div className="w-10 h-10 rounded-xl bg-blue-50 border border-blue-100 flex items-center justify-center shrink-0 group-hover:scale-105 transition-transform">
              <FileJson className="w-5 h-5 text-blue-500" />
            </div>
            <div className="flex-1">
              <p className="text-sm font-bold text-zinc-900 group-hover:text-primary">Creator IA JSON</p>
              <p className="text-[11px] text-zinc-500">Nodos, edges y datos — importable al Studio</p>
            </div>
            {exported === 'json' ? (
              <Check className="w-4 h-4 text-emerald-500 shrink-0" />
            ) : (
              <Download className="w-4 h-4 text-zinc-300 shrink-0 group-hover:text-primary/60 transition-colors" />
            )}
          </button>

          {/* Genesis Universal Schema */}
          <button
            onClick={downloadGenesis}
            className="w-full flex items-center gap-4 p-4 rounded-2xl border border-zinc-200 bg-zinc-50 hover:bg-zinc-100 hover:border-zinc-300 transition-all group text-left"
          >
            <div className="w-10 h-10 rounded-xl bg-violet-50 border border-violet-100 flex items-center justify-center shrink-0 group-hover:scale-105 transition-transform">
              <FileJson className="w-5 h-5 text-violet-500" />
            </div>
            <div className="flex-1">
              <p className="text-sm font-bold text-zinc-900 group-hover:text-violet-600">Genesis Universal Schema</p>
              <p className="text-[11px] text-zinc-500">Esquema React optimizado para despliegue v21.0</p>
            </div>
            {exported === 'genesis' ? (
              <Check className="w-4 h-4 text-emerald-500 shrink-0" />
            ) : (
              <Download className="w-4 h-4 text-zinc-300 shrink-0 group-hover:text-violet-600/60 transition-colors" />
            )}
          </button>

          {/* PDF */}
          <button
            onClick={printPDF}
            className="w-full flex items-center gap-4 p-4 rounded-2xl border border-zinc-200 bg-zinc-50 hover:bg-zinc-100 hover:border-zinc-300 transition-all group text-left"
          >
            <div className="w-10 h-10 rounded-xl bg-rose-50 border border-rose-100 flex items-center justify-center shrink-0 group-hover:scale-105 transition-transform">
              <FileText className="w-5 h-5 text-rose-500" />
            </div>
            <div className="flex-1">
              <p className="text-sm font-bold text-zinc-900 group-hover:text-rose-600">Reporte PDF</p>
              <p className="text-[11px] text-zinc-500">Imprime o guarda como PDF desde el navegador</p>
            </div>
            {exported === 'pdf' ? (
              <Check className="w-4 h-4 text-emerald-500 shrink-0" />
            ) : (
              <Download className="w-4 h-4 text-zinc-300 shrink-0 group-hover:text-rose-500/60 transition-colors" />
            )}
          </button>

        </div>

        <div className="px-6 pb-5">
          <p className="text-[10px] text-center text-zinc-400">
            creator-ia.com · Studio v2.0
          </p>
        </div>
      </div>
    </div>
  );
}
