import { useState } from 'react';
import { X, Download, FileJson, FileText, Check } from 'lucide-react';
import { Button } from '@/components/ui/button';
import { type Node, type Edge } from '@xyflow/react';
import { toast } from 'sonner';

interface ExportModalProps {
  open: boolean;
  onClose: () => void;
  nodes: Node[];
  edges: Edge[];
  spaceName?: string;
}

export function ExportModal({ open, onClose, nodes, edges, spaceName }: ExportModalProps) {
  const [exported, setExported] = useState<string | null>(null);

  if (!open) return null;

  const slug = (spaceName || 'canvas').toLowerCase().replace(/\s+/g, '-');
  const dateStr = new Date().toISOString().slice(0, 10);

  const downloadJSON = () => {
    const payload = {
      version: '2.0',
      exported_at: new Date().toISOString(),
      space_name: spaceName || 'canvas',
      nodes: nodes.map(n => ({
        id: n.id,
        type: n.type,
        position: n.position,
        data: {
          title: (n.data as any)?.title,
          prompt: (n.data as any)?.prompt,
          model: (n.data as any)?.model,
          status: (n.data as any)?.status,
          assetUrl: (n.data as any)?.assetUrl,
        },
      })),
      edges: edges.map(e => ({
        id: e.id,
        source: e.source,
        target: e.target,
        type: e.type,
      })),
    };

    const blob = new Blob([JSON.stringify(payload, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `creator-ia-${slug}-${dateStr}.json`;
    a.click();
    URL.revokeObjectURL(url);
    setExported('json');
    toast.success('Canvas exportado como JSON');
  };

  const downloadLovable = () => {
    const components = nodes.map(n => {
      const data = n.data as any;
      return {
        id: n.id,
        type: n.type,
        name: data?.title || n.type,
        prompt: data?.prompt || '',
        model: data?.model || '',
        connections: edges
          .filter(e => e.source === n.id)
          .map(e => ({ target: e.target })),
      };
    });

    const lovablePayload = {
      schema: 'creator-ia-lovable-v1',
      app_name: spaceName || 'Creator IA Export',
      components,
      tech_stack: ['React', 'Tailwind CSS', 'TypeScript'],
      notes: 'Generated by Creator IA Pro Studio — creator-ia.com',
    };

    const blob = new Blob([JSON.stringify(lovablePayload, null, 2)], { type: 'application/json' });
    const url = URL.createObjectURL(blob);
    const a = document.createElement('a');
    a.href = url;
    a.download = `lovable-${slug}-${dateStr}.json`;
    a.click();
    URL.revokeObjectURL(url);
    setExported('lovable');
    toast.success('Exportado en formato Lovable');
  };

  const printPDF = () => {
    window.print();
    setExported('pdf');
    toast.success('Diálogo de impresión abierto — guarda como PDF');
  };

  return (
    <div className="fixed inset-0 z-[200] flex items-center justify-center">
      <div className="absolute inset-0 bg-black/60 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-full max-w-md mx-4 bg-[#191a1f] border border-white/[0.08] rounded-[2rem] shadow-2xl animate-in fade-in zoom-in-95 duration-200 overflow-hidden">

        {/* Header */}
        <div className="flex items-center justify-between px-6 py-5 border-b border-white/[0.06]">
          <div>
            <h2 className="text-sm font-bold text-white font-sans">Exportar Canvas</h2>
            <p className="text-[10px] text-white/30 mt-0.5">{nodes.length} nodo{nodes.length !== 1 ? 's' : ''} · {edges.length} conex.</p>
          </div>
          <Button variant="ghost" size="icon" onClick={onClose} className="w-8 h-8 rounded-xl text-white/20 hover:text-white hover:bg-white/5">
            <X className="w-4 h-4" />
          </Button>
        </div>

        {/* Options */}
        <div className="p-6 space-y-3">

          {/* JSON */}
          <button
            onClick={downloadJSON}
            className="w-full flex items-center gap-4 p-4 rounded-2xl border border-white/[0.06] bg-white/[0.02] hover:bg-white/[0.04] hover:border-white/[0.12] transition-all group text-left"
          >
            <div className="w-10 h-10 rounded-xl bg-[#8AB4F8]/10 border border-[#8AB4F8]/20 flex items-center justify-center shrink-0 group-hover:scale-105 transition-transform">
              <FileJson className="w-5 h-5 text-[#8AB4F8]" />
            </div>
            <div className="flex-1">
              <p className="text-sm font-bold text-white group-hover:text-white">Creator IA JSON</p>
              <p className="text-[11px] text-white/30">Nodos, edges y datos — importable al Studio</p>
            </div>
            {exported === 'json' ? (
              <Check className="w-4 h-4 text-green-400 shrink-0" />
            ) : (
              <Download className="w-4 h-4 text-white/20 shrink-0 group-hover:text-white/60 transition-colors" />
            )}
          </button>

          {/* Lovable */}
          <button
            onClick={downloadLovable}
            className="w-full flex items-center gap-4 p-4 rounded-2xl border border-white/[0.06] bg-white/[0.02] hover:bg-white/[0.04] hover:border-white/[0.12] transition-all group text-left"
          >
            <div className="w-10 h-10 rounded-xl bg-[#8AB4F8]/10 border border-[#8AB4F8]/20 flex items-center justify-center shrink-0 group-hover:scale-105 transition-transform">
              <FileJson className="w-5 h-5 text-[#8AB4F8]" />
            </div>
            <div className="flex-1">
              <p className="text-sm font-bold text-white">Lovable Format</p>
              <p className="text-[11px] text-white/30">Componentes React + schema para Lovable.dev</p>
            </div>
            {exported === 'lovable' ? (
              <Check className="w-4 h-4 text-green-400 shrink-0" />
            ) : (
              <Download className="w-4 h-4 text-white/20 shrink-0 group-hover:text-white/60 transition-colors" />
            )}
          </button>

          {/* PDF */}
          <button
            onClick={printPDF}
            className="w-full flex items-center gap-4 p-4 rounded-2xl border border-white/[0.06] bg-white/[0.02] hover:bg-white/[0.04] hover:border-white/[0.12] transition-all group text-left"
          >
            <div className="w-10 h-10 rounded-xl bg-rose-500/10 border border-rose-500/20 flex items-center justify-center shrink-0 group-hover:scale-105 transition-transform">
              <FileText className="w-5 h-5 text-rose-400" />
            </div>
            <div className="flex-1">
              <p className="text-sm font-bold text-white">Reporte PDF</p>
              <p className="text-[11px] text-white/30">Imprime o guarda como PDF desde el navegador</p>
            </div>
            {exported === 'pdf' ? (
              <Check className="w-4 h-4 text-green-400 shrink-0" />
            ) : (
              <Download className="w-4 h-4 text-white/20 shrink-0 group-hover:text-white/60 transition-colors" />
            )}
          </button>

        </div>

        <div className="px-6 pb-5">
          <p className="text-[10px] text-center text-white/15">
            creator-ia.com · Studio v2.0
          </p>
        </div>
      </div>
    </div>
  );
}
